### PR TITLE
Proposed changes for compatibility with Zephyr 3.4 (OSS version)

### PR DESCRIPTION
**Pull request by ghost**
Hi u-blox maintainers,

thank you very much for basing your firmware on top of Zepyhr and making it available via github.

Are you aware that your code works flawlessly with the latest (3.4) OSS version of Zephyr?

The proposed changes will make your code (optionally) independent of proprietary code and give you the latest features of Zephyr mainline. Tried it out with an AoA 1 kit.

Kind regards,

Florian

### CODE REVIEW

**Comment by perssonmagnus** [comment]
Thank you very much for this contribution. Much appreciated!

Due to a high work load and vacations it may, however, take a little bit of time before you get feedback.

Best Regards,
Magnus

**Comment by ghost** [comment]
> Due to a high work load and vacations it may, however, take a little bit of time before you get feedback.

No problem. It's also probably not usable as-is. But I'm willing to react to review comments and fix things up in your sense.

**Comment by jakkra** [comment]
@fgrandel thanks for this, at some point soon-ish I'll update this project to also work with NCS 2.4.0 and most things in this PR is related to that also. So I'll handle this PR as part fo that work. `CMakePresets.json` is something new to me, so need to read up on that.

**Comment by ghost** [comment]
> at some point soon-ish I'll update this project to also work with NCS 2.4.0 and most things in this PR is related to that also

Sure, just tag me if there is any question.

**Pull request closed without merging**
