### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lihua-ublox**
added disclaimer

### CODE REVIEW

**Review by lihua-ublox — COMMENTED** [review]
added a disclaimer

**Comment by lihua-ublox** [comment]
added a disclaimer

**Review by lihua-ublox — COMMENTED** [review]
remove license info

**Review by perssonmagnus — COMMENTED** [review]
LGTM

**Comment by jakkra** [comment]
Are you changing licence?
If so you need to update https://github.com/u-blox/c209-aoa-tag/blob/master/LICENCE
and also update the header in all c source files.

**Comment by lihua-ublox** [comment]
> Are you changing licence? If so you need to update https://github.com/u-blox/c209-aoa-tag/blob/master/LICENCE and also update the header in all c source files.

We are not changing licence, we are adding disclaimer in the README file and removing the license statement since they both are replicate.

**Comment by jakkra** [comment]
> > Are you changing licence? If so you need to update https://github.com/u-blox/c209-aoa-tag/blob/master/LICENCE and also update the header in all c source files.
> 
> We are not changing licence, we are adding disclaimer in the README file and removing the license statement since they both are replicate.

OK 👍

**Review by perssonmagnus — APPROVED** [review]
LGTM

**Pull request merged**
